on:
  schedule:
    - cron:  '*/6 * * * *'
name: qa relase automation
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: get date
        id: date
        run: export TZ=America/Chicago && echo "::set-output name=date::$(date +'%Y-%m-%d-%H%M')"
      - run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} gh release create qa/${{ steps.date.outputs.date }} --repo ${{ github.repository }}