name: GitHub Actions Demo
on: 
  schedule:
    - cron:  '* * * * *'
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

